# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MyDextr
                                 A QGIS plugin
 This plugin is used to capture objects in a photo.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-07
        copyright            : (C) 2018 by siriusk
        email                : kai475@163.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MyDextr class from file MyDextr.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mydextr import MyDextr
    return MyDextr(iface)
